#include <furi.h>
#include <furi_hal.h>
#include <gui/modules/byte_input.h>
#include <gui/modules/variable_item_list.h>
#include <gui/view_dispatcher.h>
#include <storage/storage.h>
#include <toolbox/saved_struct.h>
#include <stdio.h>

/* generated by fbt from .png files in images folder */
#include <rgb_backlight_settings_icons.h>

#define RGBBL_TAG "RgbBacklight"

#define RGBBL_LED_COUNT 3

#define RGBBL_SETTINGS_PATH INT_PATH(".rgb_backlight.settings")
#define RGBBL_SETTINGS_MAGIC 0x52
#define RGBBL_SETTINGS_VERSION 0x01

#define RGBBL_DEFAULT_SPEED 5u
#define RGBBL_MAX_SPEED 25u
#define RGBBL_MIN_INTERVAL_MS 100u
#define RGBBL_MAX_INTERVAL_MS 5000u
#define RGBBL_TICK_MS 50u

#define RGBBL_T1H_CYCLES 30u
#define RGBBL_T1L_CYCLES 26u
#define RGBBL_T0H_CYCLES 11u
#define RGBBL_T0L_CYCLES 43u

typedef enum {
    RgbblViewList,
    RgbblViewColorInput,
} RgbblView;

typedef enum {
    RgbblCustomEventColorSaved = 1,
} RgbblCustomEvent;

typedef enum {
    RgbblModeStatic = 0,
    RgbblModeWave,
    RgbblModeSolid,
    RgbblModeCount,
} RgbblMode;

typedef struct {
    uint8_t r;
    uint8_t g;
    uint8_t b;
} RgbblColor;

typedef struct {
    uint8_t enabled;
    uint8_t mode;
    uint8_t speed;
    uint8_t saturation;
    uint32_t interval_ms;
    RgbblColor colors[RGBBL_LED_COUNT];
} RgbblSettings;

typedef struct {
    Gui* gui;
    ViewDispatcher* view_dispatcher;
    VariableItemList* variable_item_list;
    ByteInput* byte_input;
    VariableItem* color_items[RGBBL_LED_COUNT];
    RgbblSettings settings;
    uint8_t color_input[3];
    uint8_t editing_led;
    uint8_t preview_hue;
    uint32_t preview_elapsed_ms;
} RgbblApp;

static const GpioPin rgbbl_pin = {.port = GPIOA, .pin = LL_GPIO_PIN_8};

static const char* const rgbbl_on_off_text[] = {
    "OFF",
    "ON",
};

static const char* const rgbbl_mode_text[RgbblModeCount] = {
    "Static",
    "Wave",
    "Solid",
};

static const char* const rgbbl_interval_text[] = {
    "0.1s",
    "0.2s",
    "0.25s",
    "0.5s",
    "0.75s",
    "1s",
    "1.25s",
    "1.5s",
    "1.75s",
    "2s",
    "2.5s",
    "3s",
    "4s",
    "5s",
};

static const uint32_t rgbbl_interval_value[] = {
    100,
    200,
    250,
    500,
    750,
    1000,
    1250,
    1500,
    1750,
    2000,
    2500,
    3000,
    4000,
    5000,
};

static uint8_t rgbbl_value_index_uint32(
    uint32_t value,
    const uint32_t values[],
    uint8_t values_count) {
    for(uint8_t i = 0; i < values_count; i++) {
        if(values[i] == value) {
            return i;
        }
    }

    return 0;
}

static void rgbbl_settings_defaults(RgbblSettings* settings) {
    *settings = (RgbblSettings){
        .enabled = 0,
        .mode = RgbblModeStatic,
        .speed = RGBBL_DEFAULT_SPEED,
        .saturation = 255,
        .interval_ms = 250,
        .colors = {
            {.r = 255, .g = 69, .b = 0},
            {.r = 255, .g = 69, .b = 0},
            {.r = 255, .g = 69, .b = 0},
        },
    };
}

static void rgbbl_settings_validate(RgbblSettings* settings) {
    settings->enabled = settings->enabled ? 1u : 0u;

    if(settings->mode >= RgbblModeCount) {
        settings->mode = RgbblModeStatic;
    }

    if(settings->speed == 0) {
        settings->speed = 1;
    } else if(settings->speed > RGBBL_MAX_SPEED) {
        settings->speed = RGBBL_MAX_SPEED;
    }

    if(settings->saturation == 0) {
        settings->saturation = 1;
    }

    if(settings->interval_ms < RGBBL_MIN_INTERVAL_MS) {
        settings->interval_ms = RGBBL_MIN_INTERVAL_MS;
    } else if(settings->interval_ms > RGBBL_MAX_INTERVAL_MS) {
        settings->interval_ms = RGBBL_MAX_INTERVAL_MS;
    }
}

static void rgbbl_settings_load(RgbblSettings* settings) {
    rgbbl_settings_defaults(settings);
    saved_struct_load(
        RGBBL_SETTINGS_PATH,
        settings,
        sizeof(*settings),
        RGBBL_SETTINGS_MAGIC,
        RGBBL_SETTINGS_VERSION);
    rgbbl_settings_validate(settings);
}

static void rgbbl_settings_save(const RgbblSettings* settings) {
    saved_struct_save(
        RGBBL_SETTINGS_PATH,
        settings,
        sizeof(*settings),
        RGBBL_SETTINGS_MAGIC,
        RGBBL_SETTINGS_VERSION);
}

static void rgbbl_wait_cycles(uint32_t cycles) {
    uint32_t end = DWT->CYCCNT + cycles;
    while((int32_t)(DWT->CYCCNT - end) < 0) {
    }
}

static void rgbbl_write_leds(const uint8_t frame[RGBBL_LED_COUNT][3]) {
    furi_hal_gpio_write(&rgbbl_pin, false);
    furi_hal_gpio_init(&rgbbl_pin, GpioModeOutputPushPull, GpioPullNo, GpioSpeedVeryHigh);

    FURI_CRITICAL_ENTER();
    for(uint8_t led = 0; led < RGBBL_LED_COUNT; led++) {
        for(uint8_t channel = 0; channel < 3; channel++) {
            for(uint8_t mask = 0x80; mask != 0; mask >>= 1) {
                const bool one = (frame[led][channel] & mask) != 0;
                furi_hal_gpio_write(&rgbbl_pin, true);
                rgbbl_wait_cycles(one ? RGBBL_T1H_CYCLES : RGBBL_T0H_CYCLES);
                furi_hal_gpio_write(&rgbbl_pin, false);
                rgbbl_wait_cycles(one ? RGBBL_T1L_CYCLES : RGBBL_T0L_CYCLES);
            }
        }
    }
    FURI_CRITICAL_EXIT();

    furi_delay_us(80);
}

static RgbblColor rgbbl_hsv_to_rgb(uint8_t hue, uint8_t saturation, uint8_t value) {
    RgbblColor color = {.r = value, .g = value, .b = value};
    if(saturation == 0) {
        return color;
    }

    const uint8_t region = hue / 43u;
    const uint8_t remainder = (hue - (region * 43u)) * 6u;
    const uint8_t p = ((uint16_t)value * (255u - saturation)) >> 8;
    const uint8_t q = ((uint16_t)value * (255u - (((uint16_t)saturation * remainder) >> 8))) >> 8;
    const uint8_t t =
        ((uint16_t)value * (255u - (((uint16_t)saturation * (255u - remainder)) >> 8))) >> 8;

    switch(region) {
    case 0:
        color.r = value;
        color.g = t;
        color.b = p;
        break;
    case 1:
        color.r = q;
        color.g = value;
        color.b = p;
        break;
    case 2:
        color.r = p;
        color.g = value;
        color.b = t;
        break;
    case 3:
        color.r = p;
        color.g = q;
        color.b = value;
        break;
    case 4:
        color.r = t;
        color.g = p;
        color.b = value;
        break;
    default:
        color.r = value;
        color.g = p;
        color.b = q;
        break;
    }

    return color;
}

static void rgbbl_render(const RgbblApp* app) {
    uint8_t frame[RGBBL_LED_COUNT][3] = {0};

    if(app->settings.enabled) {
        if(app->settings.mode == RgbblModeStatic) {
            for(uint8_t led = 0; led < RGBBL_LED_COUNT; led++) {
                frame[led][0] = app->settings.colors[led].g;
                frame[led][1] = app->settings.colors[led].r;
                frame[led][2] = app->settings.colors[led].b;
            }
        } else {
            for(uint8_t led = 0; led < RGBBL_LED_COUNT; led++) {
                uint8_t hue = app->preview_hue;
                if(app->settings.mode == RgbblModeWave) {
                    hue = (uint8_t)(hue + (50u * led));
                }

                const RgbblColor color =
                    rgbbl_hsv_to_rgb(hue, app->settings.saturation, 255);
                frame[led][0] = color.g;
                frame[led][1] = color.r;
                frame[led][2] = color.b;
            }
        }
    }

    rgbbl_write_leds(frame);
}

static void rgbbl_update_color_text(RgbblApp* app, uint8_t led_index) {
    char text[7];
    const RgbblColor* color = &app->settings.colors[led_index];
    snprintf(text, sizeof(text), "%02X%02X%02X", color->r, color->g, color->b);
    variable_item_set_current_value_text(app->color_items[led_index], text);
}

static void rgbbl_apply_and_save(RgbblApp* app, bool reset_preview) {
    rgbbl_settings_validate(&app->settings);
    if(reset_preview) {
        app->preview_elapsed_ms = 0;
    }
    rgbbl_settings_save(&app->settings);
    rgbbl_render(app);
}

static void rgbbl_enabled_changed(VariableItem* item) {
    RgbblApp* app = variable_item_get_context(item);
    const bool enabled = variable_item_get_current_value_index(item);

    app->settings.enabled = enabled ? 1u : 0u;
    variable_item_set_current_value_text(item, rgbbl_on_off_text[enabled]);
    rgbbl_apply_and_save(app, true);
}

static void rgbbl_mode_changed(VariableItem* item) {
    RgbblApp* app = variable_item_get_context(item);
    const uint8_t mode = variable_item_get_current_value_index(item);

    app->settings.mode = mode;
    variable_item_set_current_value_text(item, rgbbl_mode_text[mode]);
    rgbbl_apply_and_save(app, true);
}

static void rgbbl_speed_changed(VariableItem* item) {
    RgbblApp* app = variable_item_get_context(item);
    char text[4];

    app->settings.speed = variable_item_get_current_value_index(item) + 1;
    snprintf(text, sizeof(text), "%u", app->settings.speed);
    variable_item_set_current_value_text(item, text);
    rgbbl_apply_and_save(app, false);
}

static void rgbbl_interval_changed(VariableItem* item) {
    RgbblApp* app = variable_item_get_context(item);
    const uint8_t index = variable_item_get_current_value_index(item);

    app->settings.interval_ms = rgbbl_interval_value[index];
    variable_item_set_current_value_text(item, rgbbl_interval_text[index]);
    rgbbl_apply_and_save(app, true);
}

static void rgbbl_saturation_changed(VariableItem* item) {
    RgbblApp* app = variable_item_get_context(item);
    char text[4];

    app->settings.saturation = variable_item_get_current_value_index(item) + 1;
    snprintf(text, sizeof(text), "%u", app->settings.saturation);
    variable_item_set_current_value_text(item, text);
    rgbbl_apply_and_save(app, false);
}

static uint32_t rgbbl_list_back_callback(void* context) {
    UNUSED(context);
    return VIEW_NONE;
}

static uint32_t rgbbl_color_back_callback(void* context) {
    RgbblApp* app = context;
    byte_input_set_result_callback(app->byte_input, NULL, NULL, NULL, NULL, 0);
    byte_input_set_header_text(app->byte_input, "");
    return RgbblViewList;
}

static void rgbbl_color_done_callback(void* context) {
    RgbblApp* app = context;
    view_dispatcher_send_custom_event(app->view_dispatcher, RgbblCustomEventColorSaved);
}

static bool rgbbl_custom_event_callback(void* context, uint32_t event) {
    RgbblApp* app = context;

    if(event != RgbblCustomEventColorSaved) {
        return false;
    }

    app->settings.colors[app->editing_led] = (RgbblColor){
        .r = app->color_input[0],
        .g = app->color_input[1],
        .b = app->color_input[2],
    };

    rgbbl_update_color_text(app, app->editing_led);
    rgbbl_apply_and_save(app, false);
    byte_input_set_result_callback(app->byte_input, NULL, NULL, NULL, NULL, 0);
    byte_input_set_header_text(app->byte_input, "");
    view_dispatcher_switch_to_view(app->view_dispatcher, RgbblViewList);
    return true;
}

static void rgbbl_enter_callback(void* context, uint32_t index) {
    RgbblApp* app = context;

    if(index < 2 || index > 4) {
        return;
    }

    app->editing_led = index - 2;
    app->color_input[0] = app->settings.colors[app->editing_led].r;
    app->color_input[1] = app->settings.colors[app->editing_led].g;
    app->color_input[2] = app->settings.colors[app->editing_led].b;

    char header[30];
    snprintf(header, sizeof(header), "Set RGB LED %u (#RRGGBB)", app->editing_led + 1);
    byte_input_set_header_text(app->byte_input, header);
    byte_input_set_result_callback(
        app->byte_input,
        rgbbl_color_done_callback,
        NULL,
        app,
        app->color_input,
        sizeof(app->color_input));
    view_dispatcher_switch_to_view(app->view_dispatcher, RgbblViewColorInput);
}

static void rgbbl_tick_callback(void* context) {
    RgbblApp* app = context;

    if(!app->settings.enabled) {
        return;
    }

    if(app->settings.mode == RgbblModeStatic) {
        return;
    }

    app->preview_elapsed_ms += RGBBL_TICK_MS;
    if(app->preview_elapsed_ms < app->settings.interval_ms) {
        return;
    }

    app->preview_elapsed_ms = 0;
    app->preview_hue += app->settings.speed;
    rgbbl_render(app);
}

static RgbblApp* rgbbl_app_alloc(void) {
    RgbblApp* app = malloc(sizeof(RgbblApp));
    rgbbl_settings_load(&app->settings);
    app->editing_led = 0;
    app->preview_hue = 0;
    app->preview_elapsed_ms = 0;

    app->gui = furi_record_open(RECORD_GUI);
    app->view_dispatcher = view_dispatcher_alloc();
    app->variable_item_list = variable_item_list_alloc();
    app->byte_input = byte_input_alloc();

    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(app->view_dispatcher, rgbbl_custom_event_callback);
    view_dispatcher_set_tick_event_callback(app->view_dispatcher, rgbbl_tick_callback, RGBBL_TICK_MS);
    view_dispatcher_attach_to_gui(app->view_dispatcher, app->gui, ViewDispatcherTypeFullscreen);

    View* view = variable_item_list_get_view(app->variable_item_list);
    view_set_previous_callback(view, rgbbl_list_back_callback);
    variable_item_list_set_enter_callback(app->variable_item_list, rgbbl_enter_callback, app);
    view_dispatcher_add_view(app->view_dispatcher, RgbblViewList, view);

    view = byte_input_get_view(app->byte_input);
    view_set_previous_callback(view, rgbbl_color_back_callback);
    view_dispatcher_add_view(app->view_dispatcher, RgbblViewColorInput, view);

    VariableItem* item;
    uint8_t index;

    item = variable_item_list_add(app->variable_item_list, "Enabled", 2, rgbbl_enabled_changed, app);
    index = app->settings.enabled ? 1 : 0;
    variable_item_set_current_value_index(item, index);
    variable_item_set_current_value_text(item, rgbbl_on_off_text[index]);

    item = variable_item_list_add(app->variable_item_list, "Mode", RgbblModeCount, rgbbl_mode_changed, app);
    index = app->settings.mode;
    variable_item_set_current_value_index(item, index);
    variable_item_set_current_value_text(item, rgbbl_mode_text[index]);

    for(uint8_t led = 0; led < RGBBL_LED_COUNT; led++) {
        char label[10];
        snprintf(label, sizeof(label), "RGB LED %u", led + 1);
        app->color_items[led] = variable_item_list_add(app->variable_item_list, label, 1, NULL, app);
        variable_item_set_current_value_index(app->color_items[led], 0);
        rgbbl_update_color_text(app, led);
    }

    item = variable_item_list_add(app->variable_item_list, "Speed", 25, rgbbl_speed_changed, app);
    index = app->settings.speed == 0 ? 0 : app->settings.speed - 1;
    variable_item_set_current_value_index(item, index);
    char speed_text[4];
    snprintf(speed_text, sizeof(speed_text), "%u", app->settings.speed);
    variable_item_set_current_value_text(item, speed_text);

    item = variable_item_list_add(
        app->variable_item_list,
        "Interval",
        COUNT_OF(rgbbl_interval_value),
        rgbbl_interval_changed,
        app);
    index = rgbbl_value_index_uint32(
        app->settings.interval_ms, rgbbl_interval_value, COUNT_OF(rgbbl_interval_value));
    variable_item_set_current_value_index(item, index);
    variable_item_set_current_value_text(item, rgbbl_interval_text[index]);

    item = variable_item_list_add(app->variable_item_list, "Saturation", 255, rgbbl_saturation_changed, app);
    index = app->settings.saturation == 0 ? 0 : app->settings.saturation - 1;
    variable_item_set_current_value_index(item, index);
    char saturation_text[4];
    snprintf(saturation_text, sizeof(saturation_text), "%u", app->settings.saturation);
    variable_item_set_current_value_text(item, saturation_text);

    rgbbl_render(app);
    view_dispatcher_switch_to_view(app->view_dispatcher, RgbblViewList);
    return app;
}

static void rgbbl_app_free(RgbblApp* app) {
    view_dispatcher_remove_view(app->view_dispatcher, RgbblViewList);
    view_dispatcher_remove_view(app->view_dispatcher, RgbblViewColorInput);
    variable_item_list_free(app->variable_item_list);
    byte_input_free(app->byte_input);
    view_dispatcher_free(app->view_dispatcher);
    furi_record_close(RECORD_GUI);
    free(app);
}

int32_t rgb_backlight_settings_app(void* p) {
    UNUSED(p);

    RgbblApp* app = rgbbl_app_alloc();
    FURI_LOG_I(RGBBL_TAG, "starting configurator");
    view_dispatcher_run(app->view_dispatcher);
    rgbbl_settings_save(&app->settings);
    rgbbl_app_free(app);

    return 0;
}
